<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Bank Manager Logged in successfully :)]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Approach" duration-ms="2795" started-at="2020-03-26T18:02:34 IST" finished-at="2020-03-26T18:02:37 IST">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="2451" started-at="2020-03-26T18:02:34 IST" finished-at="2020-03-26T18:02:36 IST">
      <class name="com.org.testcases.BankManagerLoginTest">
        <test-method status="PASS" signature="bankMngLogin()[pri:0, instance:com.org.testcases.BankManagerLoginTest@662b4c69]" name="bankMngLogin" duration-ms="2375" started-at="2020-03-26T18:02:34 IST" finished-at="2020-03-26T18:02:36 IST">
          <reporter-output>
            <line>
              <![CDATA[Bank Manager Logged in successfully :)]]>
            </line>
          </reporter-output>
        </test-method> <!-- bankMngLogin -->
      </class> <!-- com.org.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="46" started-at="2020-03-26T18:02:37 IST" finished-at="2020-03-26T18:02:37 IST">
      <class name="com.org.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.org.testcases.AddCustomerTest@48f278eb]" name="setUp" is-config="true" duration-ms="19632" started-at="2020-03-26T18:02:14 IST" finished-at="2020-03-26T18:02:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.org.testcases.AddCustomerTest@48f278eb]" name="addCustomer" duration-ms="0" started-at="2020-03-26T18:02:37 IST" data-provider="dp1" finished-at="2020-03-26T18:02:37 IST">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NegativeArraySizeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:51)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:147)
at org.testng.internal.Parameters.handleParameters(Parameters.java:801)
at org.testng.internal.Parameters.handleParameters(Parameters.java:744)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:783)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NegativeArraySizeException
at com.org.utilities.TestUtil.getData(TestUtil.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:78)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:47)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.org.testcases.AddCustomerTest@48f278eb]" name="tearDown" is-config="true" duration-ms="375" started-at="2020-03-26T18:02:37 IST" finished-at="2020-03-26T18:02:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.org.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Approach -->
</testng-results>
